In [2]:
import pandas as pd
import ast

In [3]:
anime = pd.read_csv("animes.csv")
reviews = pd.read_csv("reviews.csv")
anime.head()

,uid,title,synopsis,genre,aired,episodes,members,popularity,ranked,score,img_url,link
0,28891,Haikyuu!! Second Season,Following their participation at the Inter-Hig...,"['Comedy', 'Sports', 'Drama', 'School', 'Shoun...","Oct 4, 2015 to Mar 27, 2016",25.0,489888,141,25.0,8.82,https://cdn.myanimelist.net/images/anime/9/766...,https://myanimelist.net/anime/28891/Haikyuu_Se...
1,23273,Shigatsu wa Kimi no Uso,Music accompanies the path of the human metron...,"['Drama', 'Music', 'Romance', 'School', 'Shoun...","Oct 10, 2014 to Mar 20, 2015",22.0,995473,28,24.0,8.83,https://cdn.myanimelist.net/images/anime/3/671...,https://myanimelist.net/anime/23273/Shigatsu_w...
2,34599,Made in Abyss,The Abyss—a gaping chasm stretching down into ...,"['Sci-Fi', 'Adventure', 'Mystery', 'Drama', 'F...","Jul 7, 2017 to Sep 29, 2017",13.0,581663,98,23.0,8.83,https://cdn.myanimelist.net/images/anime/6/867...,https://myanimelist.net/anime/34599/Made_in_Abyss
3,5114,Fullmetal Alchemist: Brotherhood,"""In order for something to be obtained, someth...","['Action', 'Military', 'Adventure', 'Comedy', ...","Apr 5, 2009 to Jul 4, 2010",64.0,1615084,4,1.0,9.23,https://cdn.myanimelist.net/images/anime/1223/...,https://myanimelist.net/anime/5114/Fullmetal_A...
4,31758,Kizumonogatari III: Reiketsu-hen,After helping revive the legendary vampire Kis...,"['Action', 'Mystery', 'Supernatural', 'Vampire']","Jan 6, 2017",1.0,214621,502,22.0,8.83,https://cdn.myanimelist.net/images/anime/3/815...,https://myanimelist.net/anime/31758/Kizumonoga...

In [5]:
anime.dtypes

uid             int64
title          object
synopsis       object
genre          object
aired          object
episodes      float64
members         int64
popularity      int64
ranked        float64
score         float64
img_url        object
link           object
dtype: object

In [6]:
anime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19311 entries, 0 to 19310
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   uid         19311 non-null  int64
 1   title       19311 non-null  object
 2   synopsis    18336 non-null  object
 3   genre       19311 non-null  object
 4   aired       19311 non-null  object
 5   episodes    18605 non-null  float64
 6   members     19311 non-null  int64
 7   popularity  19311 non-null  int64
 8   ranked      16099 non-null  float64
 9   score       18732 non-null  float64
 10  img_url     19131 non-null  object
 11  link        19311 non-null  object
dtypes: float64(3), int64(3), object(6)
memory usage: 1.8+ MB

In [7]:
anime.isnull().sum()

uid              0
title            0
synopsis       975
genre            0
aired            0
episodes       706
members          0
popularity       0
ranked        3212
score          579
img_url        180
link             0
dtype: int64

In [8]:
# Parse the stringed list into an actual Python list
def extract_genres(genre_string):
    try:
        # Remove any leading/trailing whitespace and evaluate the string as a list
        genres = ast.literal_eval(genre_string.strip())
        # Ensure we have a flat list of genres
        return [g.strip() for g in genres if isinstance(g, str)]
    except (ValueError, SyntaxError):
        # If evaluation fails, return an empty list
        return []

# Convert the genre column to a list
genre_lists = anime['genre'].tolist()

# Extract genres from each stringed list
all_genres = [genre for genres in genre_lists for genre in extract_genres(genres)]

# Get unique genres
genres = sorted(set(all_genres))

In [9]:
genres

['Action',
 'Adventure',
 'Cars',
 'Comedy',
 'Dementia',
 'Demons',
 'Drama',
 'Ecchi',
 'Fantasy',
 'Game',
 'Harem',
 'Hentai',
 'Historical',
 'Horror',
 'Josei',
 'Kids',
 'Magic',
 'Martial Arts',
 'Mecha',
 'Military',
 'Music',
 'Mystery',
 'Parody',
 'Police',
 'Psychological',
 'Romance',
 'Samurai',
 'School',
 'Sci-Fi',
 'Seinen',
 'Shoujo',
 'Shoujo Ai',
 'Shounen',
 'Shounen Ai',
 'Slice of Life',
 'Space',
 'Sports',
 'Super Power',
 'Supernatural',
 'Thriller',
 'Vampire',
 'Yaoi',
 'Yuri']

In [10]:
anime_genres = dict()
for genre in genres:
    anime_genres[genre] = []

In [11]:
# One hot encode the genres
for genre_list in genre_lists:
    for genre in genres:
        if genre in genre_list:
            anime_genres[genre].append(1)
        else:
            anime_genres[genre].append(0)

In [17]:
embeddings = pd.DataFrame(anime_genres)
embeddings.set_index(anime["uid"], inplace=True)
embeddings

,Action,Adventure,Cars,Comedy,Dementia,Demons,Drama,Ecchi,Fantasy,Game,...,Shounen Ai,Slice of Life,Space,Sports,Super Power,Supernatural,Thriller,Vampire,Yaoi,Yuri
uid,,,,,,,,,,,,,,,,,,,,,
28891,0,0,0,1,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0
23273,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34599,0,1,0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
5114,1,1,0,1,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
31758,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32979,0,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
123,0,1,0,1,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1281,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
450,1,1,0,1,0,1,1,0,1,0,...,0,0,0,0,0,1,0,0,0,0
87,0,0,0,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0

In [13]:
anime.columns

Index(['uid', 'title', 'synopsis', 'genre', 'aired', 'episodes', 'members',
       'popularity', 'ranked', 'score', 'img_url', 'link'],
      dtype='object')

In [18]:
embeddings = embeddings.to_numpy()

In [20]:
embeddings.shape

(19311, 43)

In [34]:
reviews.set_index(reviews["uid"], inplace=True)
reviews = reviews.drop(["uid"], axis=1)
reviews.head()

,profile,anime_uid,text,score,scores,link
uid,,,,,,
255938,DesolatePsyche,34096,\n \n \n \n ...,8,"{'Overall': '8', 'Story': '8', 'Animation': '8...",https://myanimelist.net/reviews.php?id=255938
259117,baekbeans,34599,\n \n \n \n ...,10,"{'Overall': '10', 'Story': '10', 'Animation': ...",https://myanimelist.net/reviews.php?id=259117
253664,skrn,28891,\n \n \n \n ...,7,"{'Overall': '7', 'Story': '7', 'Animation': '9...",https://myanimelist.net/reviews.php?id=253664
8254,edgewalker00,2904,\n \n \n \n ...,9,"{'Overall': '9', 'Story': '9', 'Animation': '9...",https://myanimelist.net/reviews.php?id=8254
291149,aManOfCulture99,4181,\n \n \n \n ...,10,"{'Overall': '10', 'Story': '10', 'Animation': ...",https://myanimelist.net/reviews.php?id=291149

In [35]:
reviews[reviews["profile"] == "DesolatePsyche"]

,profile,anime_uid,text,score,scores,link
uid,,,,,,
255938,DesolatePsyche,34096,\n \n \n \n ...,8,"{'Overall': '8', 'Story': '8', 'Animation': '8...",https://myanimelist.net/reviews.php?id=255938
255793,DesolatePsyche,12403,\n \n \n \n ...,6,"{'Overall': '6', 'Story': '6', 'Animation': '9...",https://myanimelist.net/reviews.php?id=255793
298207,DesolatePsyche,35073,\n \n \n \n ...,6,"{'Overall': '6', 'Story': '6', 'Animation': '8...",https://myanimelist.net/reviews.php?id=298207
255795,DesolatePsyche,23225,\n \n \n \n ...,7,"{'Overall': '7', 'Story': '8', 'Animation': '9...",https://myanimelist.net/reviews.php?id=255795
291256,DesolatePsyche,2035,\n \n \n \n ...,8,"{'Overall': '8', 'Story': '9', 'Animation': '7...",https://myanimelist.net/reviews.php?id=291256
...,...,...,...,...,...,...
275138,DesolatePsyche,35466,\n \n \n \n ...,9,"{'Overall': '9', 'Story': '8', 'Animation': '7...",https://myanimelist.net/reviews.php?id=275138
264911,DesolatePsyche,5074,\n \n \n \n ...,7,"{'Overall': '7', 'Story': '7', 'Animation': '8...",https://myanimelist.net/reviews.php?id=264911
266432,DesolatePsyche,18245,\n \n \n \n ...,9,"{'Overall': '9', 'Story': '9', 'Animation': '1...",https://myanimelist.net/reviews.php?id=266432
278786,DesolatePsyche,1699,\n \n \n \n ...,6,"{'Overall': '6', 'Story': '6', 'Animation': '7...",https://myanimelist.net/reviews.php?id=278786
260120,DesolatePsyche,477,\n \n \n \n ...,7,"{'Overall': '7', 'Story': '8', 'Animation': '8...",https://myanimelist.net/reviews.php?id=260120

In [36]:
anime[anime["uid"] == 34096]

,uid,title,synopsis,genre,aired,episodes,members,popularity,ranked,score,img_url,link
11,34096,Gintama.,After joining the resistance against the bakuf...,"['Action', 'Comedy', 'Historical', 'Parody', '...","Jan 9, 2017 to Mar 27, 2017",12.0,139309,800,15.0,8.94,https://cdn.myanimelist.net/images/anime/3/835...,https://myanimelist.net/anime/34096/Gintama
3088,34096,Gintama.,After joining the resistance against the bakuf...,"['Action', 'Comedy', 'Historical', 'Parody', '...","Jan 9, 2017 to Mar 27, 2017",12.0,139309,800,15.0,8.94,https://cdn.myanimelist.net/images/anime/3/835...,https://myanimelist.net/anime/34096/Gintama